#!/usr/bin/env bash
# scripts/verify-attribution.sh
#
# Refuses to let any commit on the current branch (since dev) contain an AI
# attribution trailer. Run before pushing. The workflow doc tells you to run
# this. You can also install it as a pre-push git hook (see end of file).

set -euo pipefail

BASE="${BASE:-dev}"
EXPECTED_AUTHOR="${EXPECTED_AUTHOR:-AmosBunde}"

# Commits on this branch that are not on BASE
commits=$(git log --format="%H" "${BASE}..HEAD" || true)

if [[ -z "$commits" ]]; then
  echo "No commits ahead of ${BASE}. Nothing to verify."
  exit 0
fi

bad=0

echo "==> Checking commits ${BASE}..HEAD for AI attribution and author identity"

for sha in $commits; do
  msg=$(git log -1 --format="%B" "$sha")
  author_name=$(git log -1 --format="%an" "$sha")
  author_email=$(git log -1 --format="%ae" "$sha")
  subject=$(git log -1 --format="%s" "$sha")

  # Check for AI attribution trailers and phrases.
  if echo "$msg" | grep -qiE 'co-authored-by:.*(claude|anthropic|gpt|openai|copilot|cursor|ai assistant)'; then
    echo "  FAIL ${sha:0:8} ${subject}"
    echo "       co-authored-by trailer attributes to an AI tool"
    bad=$((bad+1))
  fi

  if echo "$msg" | grep -qiE '(generated with claude|assisted by claude|generated by claude|with claude code|using claude code)'; then
    echo "  FAIL ${sha:0:8} ${subject}"
    echo "       commit message contains AI attribution phrase"
    bad=$((bad+1))
  fi

  # Check the author identity is AmosBunde (or whatever EXPECTED_AUTHOR is).
  if [[ "$author_name" != "$EXPECTED_AUTHOR" ]]; then
    echo "  WARN ${sha:0:8} ${subject}"
    echo "       author is '${author_name}', expected '${EXPECTED_AUTHOR}'"
    echo "       fix with: git config user.name '${EXPECTED_AUTHOR}'"
    bad=$((bad+1))
  fi

  # Anthropic/Claude email is an explicit fail.
  if echo "$author_email" | grep -qiE '(claude|anthropic)'; then
    echo "  FAIL ${sha:0:8} ${subject}"
    echo "       author email '${author_email}' references claude/anthropic"
    bad=$((bad+1))
  fi
done

if [[ $bad -gt 0 ]]; then
  echo
  echo "==> Found ${bad} attribution issue(s). Refusing to proceed."
  echo
  echo "To fix the trailers in your commits without losing the work:"
  echo "  git rebase -i ${BASE}"
  echo "  # mark commits as 'reword', remove the Co-authored-by lines, save"
  echo
  echo "Or to rewrite all commits in one pass:"
  echo "  git filter-branch --msg-filter \\"
  echo "    'sed -E \"/^[Cc]o-authored-by:.*(claude|anthropic)/d; /^[Gg]enerated with [Cc]laude/d\"' \\"
  echo "    ${BASE}..HEAD"
  exit 1
fi

echo "==> All $(echo "$commits" | wc -l | tr -d ' ') commit(s) attributed to ${EXPECTED_AUTHOR}, no AI trailers found."
exit 0

# To install as a pre-push hook so this runs automatically on every push
# from this clone:
#   ln -s ../../scripts/verify-attribution.sh .git/hooks/pre-push
# The symlink inherits the script's executable bit; no chmod needed.
