"""Declarative base and shared metadata.

The naming convention mirrors PostgreSQL's own defaults so that hand-authored
migrations and future autogenerated ones agree on constraint and index names.
This keeps ``alembic revision --autogenerate`` quiet about spurious renames.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Logical schema namespaces. See ADR-0005: one Postgres instance, separated by
# schema rather than by database. ``aggregates`` is intentionally absent from
# the M1 subset (it lands with the leaderboard work, issue #10).
SCHEMAS: tuple[str, ...] = ("catalog", "runs", "traces")

NAMING_CONVENTION = {
    "ix": "%(table_name)s_%(column_0_N_name)s_idx",
    "uq": "%(table_name)s_%(column_0_N_name)s_key",
    "ck": "%(table_name)s_%(constraint_name)s_check",
    "fk": "%(table_name)s_%(column_0_name)s_fkey",
    "pk": "%(table_name)s_pkey",
}


class Base(DeclarativeBase):
    """Declarative base for every Agent Arena table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


metadata = Base.metadata
