"""FastAPI application assembly.

``uvicorn apps.api.main:app`` serves the API. The OpenAPI document is
generated by FastAPI at ``/openapi.json`` (issue #9 acceptance).
"""

from __future__ import annotations

from fastapi import FastAPI

from apps.api.routers import catalog, leaderboard, runs, traces
from apps.api.settings import ApiSettings


def create_app(settings: ApiSettings | None = None) -> FastAPI:
    resolved = settings or ApiSettings.from_env()
    app = FastAPI(
        title="Agent Arena API",
        version="0.1.0",
        description=(
            "Cost-aware, provider-agnostic evaluation platform for LLM agents. "
            "Cost-per-correct-answer is the headline leaderboard metric."
        ),
    )
    app.state.settings = resolved

    @app.get("/health", tags=["health"])
    async def health() -> dict[str, str]:
        return {"status": "ok"}

    app.include_router(catalog.router)
    app.include_router(runs.router)
    app.include_router(traces.router)
    app.include_router(leaderboard.router)
    return app


app = create_app()
